name: mafs_flutter_example
description: Example app demonstrating mafs_flutter

publish_to: 'none'

environment:
  sdk: ^3.9.0
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_math_fork: ^0.7.2
  mafs_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: false
